name: backend-dev
services:
  api:
    container_name: app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./src:/usr/src/app/src
    restart: always
    labels:
      - "com.janlibal=app-dev"
      - "environment=dev"
  postgres:
    image: janlibal/pg-multipledb
    container_name: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      #POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_MULTIPLE_DATABASES: ${MULTIPLE_DATABASES}
    restart: "no"
    volumes:
      - postgres:/var/lib/postgresql/data
    labels:
      - "com.janlibal=app-dev"
      - "environment=dev"
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass root
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: "no"
    volumes:
      - redis:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    #  - 'REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL'
    labels:
      - "com.janlibal=app-dev"
      - "environment=dev"


volumes:
  postgres:
    name: postgres-dev
    labels:
      purpose: database
      env: dev
  redis:
    name: redis-dev
    labels:
      purpose: in-mem-cache
      env: dev
    driver: local
