version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.ci
    env_file:
      - .env
    restart: "no"
  postgres:
    image: janlibal/pg-multipledb # postgres:16.3-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      #POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_MULTIPLE_DATABASES: ${MULTIPLE_DATABASES}
    restart: "no"
    volumes:
      - postgres:/var/lib/postgresql/data


  redis:
    image: redis:latest
    env_file:
      - .env
    command: redis-server --requirepass root
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: "no"
    volumes:
      - redis:/data
    environment:
    #  - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL'


volumes:
  postgres:
    name: ci-postgres
    labels:
      purpose: database
      environment: ci
  redis:
    name: ci-redis
    labels:
      purpose: in-mem-cache
      environment: ci
    driver: local
