name: backend-tests
services:
  # This is the configuration for our PostgreSQL database container
  # Note the `postgres` name is important, in out Node app when we refer
  # to  `host: "postgres"` that value is mapped on the network to the
  # address of this container.
  api:
    container_name: app-test
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./src:/usr/src/app/src
      - ./tests:/usr/src/app/tests
    restart: "no"
    labels:
      - "com.janlibal=app-test"
      - "environment=test"
  postgres:
    image: janlibal/pg-multipledb # postgres:16.3-alpine
    container_name: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      #POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_MULTIPLE_DATABASES: ${MULTIPLE_DATABASES}
    restart: "no"
    volumes:
      - postgres:/var/lib/postgresql/data
    labels:
      - "com.janlibal=app-test"
      - "environment=test"
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass root
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: "no"
    volumes:
      - redis:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    #  - 'REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL'
    labels:
      - "com.janlibal=app-test"
      - "environment=test"

volumes:
  postgres:
    name: postgres-test
    labels:
      purpose: database
      environment: test
  redis:
    name: redis-test
    labels:
      purpose: in-mem-cache
      environment: test
    driver: local
