name: backend-prod
services:
  api:
    image: "ghcr.io/janlibal/nestjs-graphql:latest"
    container_name: app
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: unless-stopped
    labels:
      - "com.mycompany=app-prod"
      - "environment=prod"
  postgres:
    image: janlibal/pg-multipledb # postgres:16.3-alpine
    container_name: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      #POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_MULTIPLE_DATABASES: ${MULTIPLE_DATABASES}
    restart: unless-stopped
    #env_file:
    #  - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass root
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: unless-stopped
    volumes:
      - redis:/data
    environment:
    #  - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL'

volumes:
  postgres:
    name: postgres-prod
    labels:
      purpose: database
      environment: prod
  redis:
    name: redis-prod
    labels:
      purpose: in-mem-cache
      environment: ci
    driver: local
