name: backend-prod
services:
  api:
    container_name: application
    image: "ghcr.io/janlibal/nestjs-graphql:latest"
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - api-network
    volumes:
      - .:/usr/src/app
    labels:
      - "com.janlibal=app-prod"
      - "environment=prod"
  postgres:
    container_name: postgres
    image: janlibal/pg-multipledb # postgres:16.3-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      #POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_MULTIPLE_DATABASES: ${MULTIPLE_DATABASES}
    restart: unless-stopped
    #env_file:
    #  - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - api-network
    labels:
      - "com.janlibal=app-prod"
      - "environment=prod"
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass root
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: unless-stopped
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "root", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - api-network
    labels:
      - "com.janlibal=app-prod"
      - "environment=prod"
    environment:
    #  - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL'

volumes:
  postgres:
    name: prod-db
    labels:
      purpose: database
      environment: prod
  redis:
    name: redis
    labels:
      purpose: in-mem-cache
      environment: ci
    driver: local

networks:
  api-network:
    name: backend-prod-network
    driver: bridge
