name: backend-tests
services:
  # This is the configuration for our PostgreSQL database container
  # Note the `postgres` name is important, in out Node app when we refer
  # to  `host: "postgres"` that value is mapped on the network to the
  # address of this container.
  api:
    container_name: app-test
    build:
      context: .
      dockerfile: relational.test.Dockerfile
    env_file:
      - env-example-relational
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./src:/usr/src/app/src
      - ./tests:/usr/src/app/tests
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: "no"
    networks:
      - api-network
    labels:
      - "com.janlibal=app-test"
      - "environment=test"
  postgres:
    container_name: postgres
    image: janlibal/pg-multipledb # postgres:16.3-alpine
    env_file:
      - env-example-relational
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      #POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_MULTIPLE_DATABASES: ${MULTIPLE_DATABASES}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: "no"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - api-network
    labels:
      - "com.janlibal=app-test"
      - "environment=test"
  # PostgreSQL pgAdmin panel accessible at http://localhost:16543/
  #pgadmin-compose:
  #  container_name: nest-pgadmin
  #  image: dpage/pgadmin4
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
  #    PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
  #  ports:
  #    #- "16543:80"
  #    - ${PGADMIN_PORT}:80
  #  depends_on:
  #    - postgres
  redis:
    container_name: redis
    image: redis:latest
    env_file:
      - env-example-relational
    command: redis-server --requirepass root
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: "no"
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "root", "ping", "--raw"]
      interval: 5s
      timeout: 3s
      retries: 5
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    #  - 'REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL'
    networks:
      - api-network
    labels:
      - "com.janlibal=app-test"
      - "environment=test"

volumes:
  postgres:
    name: test-db
    labels:
      purpose: database
      environment: test
  redis:
    name: redis
    labels:
      purpose: in-mem-cache
      environment: test
    driver: local

networks:
  api-network:
    name: backend-test-network
    driver: bridge
