name: E2E Tests

#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  changes_checker:
    runs-on: ubuntu-latest
    outputs:
      run_tests: ${{ steps.check.outputs.run_tests }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check for changes in relevant files
        id: check
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main..HEAD)
          echo "Changed files: $CHANGED_FILES"

          if [[ $CHANGED_FILES =~ ^(src/|test/).* ]]; then
            echo "Tests should be run"
            echo "run_tests=true" >> $GITHUB_ENV
            echo "run_tests=true" >> $GITHUB_OUTPUT
          else
            echo "No relevant changes, skipping tests"
            echo "run_tests=false" >> $GITHUB_ENV
            echo "run_tests=false" >> $GITHUB_OUTPUT
          fi
  run_e2e:
    runs-on: ubuntu-latest
    needs: changes_checker
    #if: ${{ needs.changes_checker.outputs.run_tests == 'true' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run e2e tests
        run: |
          docker compose -f docker-compose.ci.yml --env-file .env -p ci-relational up --build --exit-code-from api

      - name: Copy prod.log from container to host
        if: ${{ failure() && steps.relational.conclusion == 'failure' }}
        run: docker cp ci-relational-api-1:/usr/src/app/prod.log .

      - name: Upload prod.log to artifacts for debugging
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: prod-logs
          path: prod.log
