name: Deploy
permissions:
  packages: write
  contents: write
  pull-requests: write
  issues: read
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag/version to deploy (default: latest)'
        required: false
        default: 'latest'
      environment:
        description: 'Environment (e.g. prod, staging)'
        required: true
        default: 'prod'
      confirm_deploy:
        description: 'Type "yes" to confirm deployment'
        required: true
        default: 'no'
jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-22.04
    if: ${{ github.event.inputs.confirm_deploy == 'yes' }}
    steps:
      - name: Validate confirmation
        run: echo "Deployment confirmed. Proceeding..."
      - name: Assign environment variables
        run: |
          echo "TAG_NAME=${{ github.event.inputs.version || 'latest' }}" >> $GITHUB_ENV
          echo "image_repository_name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "domain=${{ secrets.HOST }}" >> $GITHUB_ENV
          echo "letsencrypt_email=${{ secrets.LETSENCRYPT_EMAIL }}" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.version || 'main' }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ env.image_repository_name }}:${{ env.TAG_NAME }}
          build-args: |
            ENV_FILE_CONTENT=${{ secrets.ENV_PROD_FILE_BASE64 }}
      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          port: 22
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "./docker-compose.yml"
          target: "~/.deploy/${{ github.event.repository.name }}/"
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.5
        env:
          APPTOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ secrets.EC2_USERNAME }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          envs: APPTOKEN,USERNAME
          script: |
            echo $APPTOKEN | docker login ghcr.io -u $USERNAME --password-stdin
            cd ~/.deploy/${{ github.event.repository.name }}
            echo "${{ secrets.ENV_PROD_FILE_BASE64 }}" | base64 --decode > .env
            sudo docker-compose -f docker-compose.yml pull api
            if ! sudo docker ps --filter "name=redis" --filter "status=running" | grep redis; then
              echo "Redis is not running. Starting Redis..."
              sudo docker-compose -f docker-compose.yml up -d redis
            else
              echo "Redis is running."
            fi
            if ! sudo docker ps --filter "name=postgres" --filter "status=running" | grep postgres; then
              echo "Postgres is not running. Starting Postgres..."
              sudo docker-compose -f docker-compose.yml up -d postgres
            else
              echo "Postgres is running."
            fi
            echo "Deploying API container"
            sudo docker-compose -f docker-compose.yml up -d --no-deps --build api
            # Clean up dangling images
            sudo docker image prune -af
      - name: Confirm Completion
        run: echo "Deployment finished for version ${{ env.TAG_NAME }}"
