name: Release
permissions:
  packages: write
  contents: write
  pull-requests: write
  issues: read
on:
  # Triggered on new GitHub Release
  release:
    types: [published]
  # Triggered on every successful Build action
  #workflow_run:
  #  workflows: ["E2E Tests"]
  #  branches: [ main ]
  #  types:
  #    - completed
  # Manual trigger for rollback to specific release or redeploy latest
  #workflow_dispatch:
  #  inputs:
  #    version:
  #      default: latest
  #      description: Tag you want to release.
  #      required: true
jobs:
  echo_it:
    runs-on: ubuntu-latest
    name: Starting echo-it job
    steps:
      - name: The echo-it message!
        run: |
          echo "The echoed message."
  push_to_registry:
    needs: echo_it
    runs-on: ubuntu-22.04
    name: Starting push-to-registry job
    if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    steps:
      # Checkout latest or specific tag
      - name: checkout
        if: ${{ github.event.inputs.version == '' || github.event.inputs.version == 'latest' }}
        uses: actions/checkout@v3
        with:
          node-version: 22
      - name: checkout tag
        if: ${{ github.event.inputs.version != '' && github.event.inputs.version != 'latest' }}
        uses: actions/checkout@v3
        with:
          ref: refs/tags/${{ github.event.inputs.version }}
          node-version: 22
      # Assign environment variables used in subsequent steps
      - name: Env variable assignment
        run: echo "image_repository_name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      # TAG_NAME defaults to 'latest' if not a release or manual deployment
      - name: Assign version
        run: |
          echo "TAG_NAME=latest" >> $GITHUB_ENV
          if [ "${{ github.event.release.tag_name }}" != "" ]; then
            echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          fi;
          if [ "${{ github.event.inputs.version }}" != "" ]; then
            echo "TAG_NAME=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi;
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Build and push new docker image, skip for manual redeploy other than 'latest'
      - name: Build and push Docker images
        run: |
          echo "Build and push DOcker image finished."
